version: '3'
services:

  qgisserver:
    image: g3wsuite/qgis3-server:ltr-ubuntu
    ports:
    - "8010:80"
    environment:
      QGIS_DEBUG: 0
      QGIS_LOG_FILE: "" #/tmp/qgis.log
      QGIS_SERVER_LOG_STDERR: 1
      QGIS_SERVER_LOG_FILE: "" # /tmp/qgis_server.log
      QGIS_SERVER_LOG_LEVEL: 3 # 2 is critical 3 is no logs
      QGIS_PROJECT_FILE: ""
      QGIS_SERVER_MAX_THREADS: 8
      PGSERVICEFILE: /shared-volume/pg_service.conf"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure
    volumes:
      - ${WEBGIS_DOCKER_SHARED_VOLUME}:/shared-volume
    networks:
      internal:

  postgis:
    image: g3wsuite/postgis:11.0-2.5
    ports:
    - "5439:5432"
    environment:
      - POSTGRES_DBNAME=${G3WSUITE_POSTGRES_DBNAME},data_testing,data_production
      - POSTGRES_USER=${G3WSUITE_POSTGRES_USER_LOCAL}
      - POSTGRES_PASS=${G3WSUITE_POSTGRES_PASS}
      - ALLOW_IP_RANGE=0.0.0.0/0
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ${WEBGIS_DOCKER_SHARED_VOLUME}:/var/lib/postgresql
    networks:
      internal:
        aliases:
          # Legacy: to be removed
          - ${WEBGIS_PUBLIC_HOSTNAME}

  g3w-suite:
    image: elpaso/g3w-suite-dev:dj22-py3
    environment:
      - G3WSUITE_TILECACHE_PATH
      - G3WSUITE_QDJANGO_SERVER_URL
      - G3WSUITE_POSTGRES_DBNAME
      - G3WSUITE_POSTGRES_USER
      - G3WSUITE_POSTGRES_USER_LOCAL
      - G3WSUITE_POSTGRES_PASS
      - G3WSUITE_POSTGRES_HOST
      - G3WSUITE_POSTGRES_PORT
      - TILESTACHE_CACHE_BUFFER_SIZE
      - PYTHONUNBUFFERED="1"
    expose:
    - "8000"
    command: >
      bash -c "/code/ci_scripts/build_suite.sh && /code/ci_scripts/setup_suite.sh && cd /code/g3w-admin && gunicorn base.wsgi:application --limit-request-fields 0 --error-logfile - --log-level=debug --timeout 120 --workers=8 -b 0.0.0.0:8000"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

    depends_on:
      - postgis
    volumes:
      - ${WEBGIS_DOCKER_SHARED_VOLUME}:/shared-volume
      - ./config/g3w-suite/overrides/templates:/code/templates:ro
      - ./config/g3w-suite/settings_docker.py:/code/g3w-admin/base/settings/local_settings.py:ro

    networks:
      internal:

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
      - "443:443"
    expose:
      - "8080"
    volumes:
      - ${WEBGIS_DOCKER_SHARED_VOLUME}:/shared-volume
      - ${WEBGIS_DOCKER_SHARED_VOLUME}/var/www/.well-known:/var/www/.well-known
      - ${WEBGIS_DOCKER_SHARED_VOLUME}/certs/letsencrypt:/etc/letsencrypt:ro
      - ./config/g3w-suite/overrides/static:/shared-volume/static/overrides:ro
      - ./config/nginx:/etc/nginx/conf.d:ro
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    networks:
      internal:

volumes:
    shared-volume:

networks:
    internal:
